# Server
server.port=8080
spring.application.name=api-gateway

# Auth Service Routes
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Resident Service Routes
spring.cloud.gateway.routes[1].id=resident-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/complaints/**

# Amenities Route
spring.cloud.gateway.routes[2].id=amenities
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/amenities/**

spring.cloud.gateway.routes[3].id=notices
spring.cloud.gateway.routes[3].uri=http://localhost:8082
spring.cloud.gateway.routes[3].predicates[0]=Path=/notices/**

spring.cloud.gateway.routes[4].id=visitor-service
spring.cloud.gateway.routes[4].uri=http://localhost:8083
spring.cloud.gateway.routes[4].predicates[0]=Path=/visitors/**

# CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

# Actuator
management.endpoints.web.exposure.include=*