# Server
server.port=8082
spring.application.name=resident-service

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/nestiq_resident
spring.datasource.username=root
spring.datasource.password=Satya@1999
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# JWT
jwt.secret=nestiq_super_secret_key_2024_must_be_at_least_256_bits_long

# Auth service URL
auth.service.url=http://localhost:8081